=== mlamm/amadeus-ws-client/tests/_data/schema/price/get-response-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "last_ticketing_date": {
      "type": "string"
    },
    "passenger_price": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "total_tax": {
              "type": "number"
            },
            "base_fare": {
              "type": "integer"
            },
            "base_fare_currency": {
              "type": "string"
            }
          },
          "required": [
            "total_tax",
            "base_fare",
            "base_fare_currency"
          ]
        },
        {
          "type": "object",
          "properties": {
            "total_tax": {
              "type": "number"
            },
            "base_fare": {
              "type": "integer"
            },
            "base_fare_currency": {
              "type": "string"
            }
          },
          "required": [
            "total_tax",
            "base_fare",
            "base_fare_currency"
          ]
        }
      ]
    },
    "validating_carrier": {
      "type": "string"
    },
    "_links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          },
          "required": [
            "href"
          ]
        }
      },
      "required": [
        "self"
      ]
    }
  },
  "required": [
    "last_ticketing_date",
    "passenger_price",
    "validating_carrier",
    "_links"
  ]
}

=== mlamm/amadeus-ws-client/tests/_data/fixtures/response/price/get-response-4-pax.json
{
  "last_ticketing_date": "2018-11-21",
  "passenger_price": [
    {
      "total_tax": 297.06,
      "base_fare": 40,
      "base_fare_currency": "EUR",
      "passenger_ref": [
        {
          "qualifier": "PA",
          "id": "2"
        },
        {
          "qualifier": "PA",
          "id": "3"
        }
      ]
    },
    {
      "total_tax": 297.06,
      "base_fare": 30,
      "base_fare_currency": "EUR",
      "passenger_ref": [
        {
          "qualifier": "PA",
          "id": "4"
        },
        {
          "qualifier": "PA",
          "id": "5"
        }
      ]
    }
  ],
  "validating_carrier": "RJ",
  "_links": {
    "self": {
      "href": "/price/"
    }
  }
}

=== mlamm/amadeus-ws-client/docs/price/get-result.json
{
  "last_ticketing_date": "2018-11-30",
  "passenger_price": [
    {
      "total_tax": 400.08,
      "base_fare": 90,
      "base_fare_currency": "EUR",
      "passenger_ref": [
        {
          "qualifier": "PA",
          "id": "2"
        }
      ]
    },
    {
      "total_tax": 0,
      "base_fare": 9,
      "base_fare_currency": "EUR",
      "passenger_ref": [
        {
          "qualifier": "PI",
          "id": "2"
        }
      ]
    }
  ],
  "validating_carrier": "CA",
  "_links": {
    "self": {
      "href": "/price/"
    }
  }
}
